---
- name: Get Kubernetes Pods
  hosts: localhost
  gather_facts: no
  tasks:
    - name: List Pods in the default namespace
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Pod
        namespace: default
      register: pod_list

    - name: Print pod details
      debug:
        msg: "{{ pod_list.resources }}"

    - name: Create a namespace for the application
      community.kubernetes.k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: teste-namespace